# Change these first
owner: cityssm # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  # - name: TCP Ping (209.105.201.112)
  #   check: "tcp-ping"
  #   url: 209.105.201.112
  # - name: TCP Ping (IP1 - 209.105.201.113)
  #   check: "tcp-ping"
  #   url: 209.105.201.113
  # - name: TCP Ping (IP2 - 209.105.201.114)
  #   check: "tcp-ping"
  #   url: 209.105.201.114
  # - name: TCP Ping (IP3 - 209.105.201.115)
  #   check: "tcp-ping"
  #   url: 209.105.201.115
  # - name: TCP Ping (IP4 - 209.105.201.116)
  #   check: "tcp-ping"
  #   url: 209.105.201.116
  # - name: TCP Ping (IP5 - 209.105.201.117)
  #   check: "tcp-ping"
  #   url: 209.105.201.117
  - name: TCP Ping (WWW - 209.105.201.118)
    check: "tcp-ping"
    url: 209.105.201.118
  # - name: TCP Ping (IP6 - 209.105.201.119)
  #   check: "tcp-ping"
  #   url: 209.105.201.119
  # - name: TCP Ping (IP7 - 209.105.201.120)
  #   check: "tcp-ping"
  #   url: 209.105.201.120
  # - name: TCP Ping (IP8 - 209.105.201.121)
  #   check: "tcp-ping"
  #   url: 209.105.201.121
  - name: TCP Ping (IP9 - 209.105.201.122)
    check: "tcp-ping"
    url: 209.105.201.122
  # - name: TCP Ping (MAIL - 209.105.201.123)
  #   check: "tcp-ping"
  #   url: 209.105.201.123
  # - name: TCP Ping (IP11 - 209.105.201.124)
  #   check: "tcp-ping"
  #   url: 209.105.201.124
  # - name: TCP Ping (IP12 - 209.105.201.125)
  #   check: "tcp-ping"
  #   url: 209.105.201.125
  - name: TCP Ping (IP13 - 209.105.201.126)
    check: "tcp-ping"
    url: 209.105.201.126
  # - name: TCP Ping (209.105.201.127)
  #   check: "tcp-ping"
  #  url: 209.105.201.127
  - name: SaultSteMarie.ca
    url: https://saultstemarie.ca/
  - name: Building Permit Services (apps.saultstemarie.ca)
    url: https://apps.saultstemarie.ca/cityapps/
  - name: Virtual City Hall (myfinance.saultstemarie.ca)
    url: https://myfinance.saultstemarie.ca/vch/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/cityssm/cityssm.github.io/master/img/header-cityssm.png
  name: SaultSteMarie.ca Upptime
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Accessibility Scans
      href: https://cityssm.github.io/lighthouse-scans/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

robotsText: "User-agent: * \n Disallow: /"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
