# Change these first
owner: cityssm # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: TCP Ping (209.105.201.118)
    check: "tcp-ping"
    url: 209.105.201.118
  - name: SaultSteMarie.ca
    url: https://saultstemarie.ca/
  - name: Building Permit Services (apps.saultstemarie.ca)
    url: https://apps.saultstemarie.ca/cityapps/
  - name: Virtual City Hall (myfinance.saultstemarie.ca)
    url: https://myfinance.saultstemarie.ca/vch/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/cityssm/cityssm.github.io/master/img/header-cityssm.png
  name: SaultSteMarie.ca Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Accessibility Scans
      href: https://cityssm.github.io/lighthouse-scans/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

robotsText: "User-agent: * \n Disallow: /"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
